version: 2

jobs:
  build:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn lint

      - run: yarn test --coverage --ci --runInBand --reporters=default --reporters=jest-junit --forceExit

      - store_test_results:
          path: junit.xml

      - run: yarn coverage
