name: build
on:
  push:
    branches:
      - master
  pull_request:
env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # fix version to 13 to support ES Modules
      - name: Use Node.js 13
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Restore Cache
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-13-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-13-
      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test --coverage --ci --runInBand --reporters=default --reporters=jest-junit --forceExit
      - name: Archive Test Results
        # if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: Test Report
          path: junit.xml

      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: github.ref == 'refs/heads/master'
